platform:ios,'7.0'

pod 'ReactiveCocoa'
pod 'Parse-iOS-SDK'
pod 'TSMessages'
pod 'RESideMenu', '~> 3.4'
pod 'JSAnimatedImagesView'
pod 'BZGFormField'
pod 'MRProgress', '~> 0.3'
pod 'SDWebImage'
pod 'PBJVision'
pod 'RPFloatingPlaceholders'
pod 'AVOSCloud'
pod 'AVOSCloudUI'
pod 'TMCache', '~> 1.2.0'
pod 'HPGrowingTextView'
pod 'iCarousel'
pod 'PopoverView'
pod 'REMenu', '~> 1.8'
pod 'EAIntroView'